let markerImagesMap = new Map();
markerImagesMap.set('Collapsed Road', 'road');
markerImagesMap.set('Blocked Road', 'ban');
markerImagesMap.set('Collapsed Powerline', 'plug');
markerImagesMap.set('Oil Spill', 'tint');
markerImagesMap.set('Gas Leak', 'exclamation triangle');
markerImagesMap.set('Sinkhole', 'emergency');
markerImagesMap.set('Flooded Area', 'attention');

markerImagesMap.set('Evacuation Bus', 'bus');
markerImagesMap.set('ADRA Management Tent', 'home');
markerImagesMap.set('Check In Tent', 'home');
markerImagesMap.set('Malaria Kit', 'medkit');
markerImagesMap.set('Vaccination Tent', 'medkit');
markerImagesMap.set('Vitamins', 'apple');
markerImagesMap.set('Evacuation Safe Zone', 'shield');
markerImagesMap.set('Missing Person Tent', 'compass');
markerImagesMap.set('Blanket', 'home');
markerImagesMap.set('Mosquito Net', 'home');
markerImagesMap.set('Refugee Camp', 'bed');
markerImagesMap.set('Camp Washroom', 'bed');
markerImagesMap.set('Camp Showers', 'bed');
markerImagesMap.set('Debris Dump', 'street view');
markerImagesMap.set('Field Hospital', 'street view');
markerImagesMap.set('School', 'graduation');
markerImagesMap.set('Food rations', 'food');
markerImagesMap.set('Community Farm', 'food');
markerImagesMap.set('Wireless Tower', 'wifi');
markerImagesMap.set('Public Phone', 'phone');
markerImagesMap.set('Water Well', 'lab');
markerImagesMap.set('Resevoir', 'lab');
markerImagesMap.set('Water Main', 'lab');
markerImagesMap.set('Water Purification Pill', 'lab');
markerImagesMap.set('Soap', 'lab');
markerImagesMap.set('Toothbrush', 'lab');

export default markerImagesMap;